name: Build and Test

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x
          
      - name: .NET Restore
        run: dotnet restore src
      
      - name: .NET Build
        run: dotnet build src --configuration Release --no-restore
      
      - name: .NET Test
        run: dotnet test **/*/Authentication.Test.csproj -configuration Release --no-build --verbosity minimal
